engines:
  phpcodesniffer:
    enabled: true
    config:
    file_extensions: "php"
  phpmd:
    enabled: true


# For more details see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# Note: If the ratings key is not specified, this will result in a 0.0 GPA on your dashboard.

# ratings:
#   paths:
#   - app/**
#   - lib/**
#   - "**.rb"
#   - "**.go"

# You can globally exclude files from being analyzed by any engine using the
# exclude_paths key.

#exclude_paths:
#- spec/**/*
#- vendor/**/*
